import React from 'react';
import {render} from 'react-dom';

import { Img, BlinkloaderProvider } from '../src/index';

const App = () => {
  return (<div>
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    <Img src='https://www.common.com/static/images/why-common/laundry@2x.jpg' width={300} lazyload={true} progressive={true} />
    </div>)
};

render(
  <BlinkloaderProvider
    projectId={process.env.BLINKLOADER_DEV_PROJECT_ID}
    token={process.env.BLINKLOADER_DEV_TOKEN}
  >
    <App />
  </BlinkloaderProvider>,
  document.querySelector('.App')
);
